import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv()
url = os.getenv("SUPABASE_URL")
key = os.getenv("SUPABASE_SERVICE_KEY")

if not url or not key:
    print("Error: Missing API keys")
    exit(1)

supabase = create_client(url, key)

sql = """
CREATE TABLE IF NOT EXISTS token_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    source TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_tokens INT DEFAULT 0,
    completion_tokens INT DEFAULT 0,
    total_tokens INT DEFAULT 0,
    meta JSONB
);

ALTER TABLE token_usage_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'token_usage_logs' AND policyname = 'Service role can do everything on token_usage_logs'
    ) THEN
        CREATE POLICY "Service role can do everything on token_usage_logs"
            ON token_usage_logs
            USING (auth.role() = 'service_role')
            WITH CHECK (auth.role() = 'service_role');
    END IF;
END
$$;
"""

try:
    # Supabase-py client doesn't support raw SQL execution easily on the free tier without RPC or specific setup.
    # But we can try using the REST API if we had a function.
    # Actually, the best way is to ask the user to run it in the dashboard.
    # However, I can try to use the 'rpc' method if I wrap this in a function, but I can't create a function without SQL.
    
    # Wait, I can use the 'postgres' connection if I had the connection string, but I only have the REST URL.
    # I will output the instructions to the user.
    print("Please run the content of 'database/monitor_usage.sql' in your Supabase SQL Editor.")
except Exception as e:
    print(f"Error: {e}")
