-- ==============================================================================
-- Eco-Neuro Sentinel: Database Initialization Script
-- ==============================================================================
-- This script initializes the persistence layer for the GDPR-compliant health
-- monitoring application. It sets up extensions, schema, indexing, and
-- strict Row Level Security (RLS) policies.

-- ------------------------------------------------------------------------------
-- 1. Enable Extensions
-- ------------------------------------------------------------------------------

-- Enable pgvector for storing OpenAI embeddings (1536 dimensions)
-- Security Note: Used for vector similarity search in the knowledge base.
CREATE EXTENSION IF NOT EXISTS vector;

-- Enable PostGIS for geospatial calculations
-- Security Note: Essential for privacy-preserving location analysis (e.g., Point-in-Polygon).
CREATE EXTENSION IF NOT EXISTS postgis;

-- ------------------------------------------------------------------------------
-- 2. Schema Definition
-- ------------------------------------------------------------------------------

-- Table: profiles
-- Description: Stores user profile information linked to Supabase Auth.
CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    sector TEXT, -- e.g., 'Sector 1'
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Table: patient_logs (High Sensitivity)
-- Description: Stores strictly isolated patient symptom logs and location data.
CREATE TABLE patient_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id),
    symptom_text TEXT, -- Raw description of symptoms
    severity_score INTEGER CHECK (severity_score >= 1 AND severity_score <= 10),
    log_location GEOGRAPHY(Point, 4326), -- Precise WGS84 coordinates
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Table: air_quality (Public Utility)
-- Description: Stores environmental data for sectors. Publicly readable by authenticated users.
CREATE TABLE air_quality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_name TEXT,
    pm25 DOUBLE PRECISION,
    pm10 DOUBLE PRECISION,
    boundary GEOGRAPHY(Polygon, 4326), -- Defines the sector's shape
    last_updated TIMESTAMPTZ DEFAULT now()
);

-- Table: knowledge_base (RAG Source)
-- Description: Stores vector embeddings for semantic search.
CREATE TABLE knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    embedding VECTOR(1536),
    metadata JSONB -- Stores source page, article number, etc.
);

-- ------------------------------------------------------------------------------
-- 3. Indexing Strategy
-- ------------------------------------------------------------------------------

-- Vector Index for knowledge_base
-- Algorithm: HNSW (Hierarchical Navigable Small World)
-- Parameters: m=16, ef_construction=64 (Balanced for build time vs. recall)
-- Operator: vector_cosine_ops (Optimized for cosine similarity)
CREATE INDEX ON knowledge_base USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- Spatial Index for patient_logs
-- Type: GiST (Generalized Search Tree)
-- Purpose: Optimizes spatial queries like ST_Intersects on log_location.
CREATE INDEX ON patient_logs USING gist (log_location);

-- Spatial Index for air_quality
-- Type: GiST
-- Purpose: Optimizes Point-in-Polygon queries using the sector boundary.
CREATE INDEX ON air_quality USING gist (boundary);

-- ------------------------------------------------------------------------------
-- 4. Row Level Security (RLS) Policies
-- ------------------------------------------------------------------------------

-- Enable RLS on all tables to enforce "Privacy by Design".
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE air_quality ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_base ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
-- Security: Users can only see and edit their own profile data.
CREATE POLICY "Users can view own profile" 
    ON profiles FOR SELECT 
    USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
    ON profiles FOR UPDATE 
    USING (auth.uid() = id);

-- Policies for patient_logs
-- Security: STRICT ISOLATION. Users can only access their own health logs.
-- No public access is permitted.
CREATE POLICY "Users can view own logs" 
    ON patient_logs FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own logs" 
    ON patient_logs FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

-- Policies for air_quality
-- Security: Publicly readable by any authenticated user.
-- Modifications are restricted to the service_role (admin/backend).
CREATE POLICY "Authenticated users can view air quality" 
    ON air_quality FOR SELECT 
    TO authenticated 
    USING (true);

-- Policies for knowledge_base
-- Security: Publicly readable by any authenticated user for RAG features.
-- Modifications are restricted to the service_role.
CREATE POLICY "Authenticated users can view knowledge base" 
    ON knowledge_base FOR SELECT 
    TO authenticated 
    USING (true);

-- ------------------------------------------------------------------------------
-- 5. RPC Function for Similarity Search
-- ------------------------------------------------------------------------------

-- Function: match_documents
-- Description: Performs a vector similarity search using cosine distance.
-- Parameters:
--   query_embedding: The vector to search for.
--   match_threshold: Minimum similarity score (0 to 1).
--   match_count: Maximum number of results to return.
CREATE OR REPLACE FUNCTION match_documents (
  query_embedding VECTOR(1536),
  match_threshold FLOAT,
  match_count INT
)
RETURNS TABLE (
  id BIGINT,
  content TEXT,
  metadata JSONB,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    knowledge_base.id,
    knowledge_base.content,
    knowledge_base.metadata,
    1 - (knowledge_base.embedding <=> query_embedding) AS similarity
  FROM knowledge_base
  WHERE 1 - (knowledge_base.embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
END;
$$;
