-- ==============================================================================
-- Token Usage Monitoring
-- ==============================================================================
-- Table to track OpenAI token usage across the platform.

CREATE TABLE IF NOT EXISTS token_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    source TEXT NOT NULL, -- e.g., 'analyze-risk-function', 'ingest-script'
    model TEXT NOT NULL, -- e.g., 'gpt-4o', 'text-embedding-3-small'
    prompt_tokens INT DEFAULT 0,
    completion_tokens INT DEFAULT 0,
    total_tokens INT DEFAULT 0,
    meta JSONB -- Optional: store extra info like user_id or context
);

-- Enable RLS
ALTER TABLE token_usage_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Service Role has full access
CREATE POLICY "Service role can do everything on token_usage_logs"
    ON token_usage_logs
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- Optional: Allow read access to authenticated users if you want to build a dashboard
-- CREATE POLICY "Auth users can view usage"
--     ON token_usage_logs FOR SELECT
--     TO authenticated
--     USING (true);
